services:
  # FastAPI Backend Service
  api:
    build: .
    container_name: labrag-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
    command: uvicorn labrag.api.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - labrag-network

  # Streamlit Frontend Service
  app:
    build: .
    container_name: labrag-app
    ports:
      - "8501:8501"
    environment:
      - LABRAG_API_URL=http://api:8000/chat/
    command: >
      sh -c "
        echo 'Waiting for API to be ready...' &&
        sleep 5 &&
        echo 'Starting Streamlit app...' &&
        streamlit run labrag/app/main.py --server.port=8501 --server.address=0.0.0.0
      "
    depends_on:
      api:
        condition: service_healthy
    networks:
      - labrag-network

networks:
  labrag-network:
    driver: bridge 